[build]
  command = "JEKYLL_ENV=production bundle exec jekyll build --config _config.yml,_config_netlify.yml"
  publish = "_site"

[build.environment]
  JEKYLL_ENV = "production"
  JEKYLL_CONFIG_BASEURL = ""

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404 